services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8087:8087"
    depends_on:
      - redis
      - postgres-db
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - dimmm-net

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - dimmm-net

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5434:5432"
    restart: always
    environment:
      - POSTGRES_DB=users-events
      - POSTGRES_USER=dimmm
      - POSTGRES_PASSWORD=12345
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - dimmm-net

  redis-insights:
    image: redis/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"
    networks:
      - dimmm-net
    restart: always
    volumes:
      - redis-insights-data:/data

volumes:
  redis-insights-data:
  postgres-data:

networks:
  dimmm-net:
    driver: bridge