spring:
  application:
    name: redis-demo-my

  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-db:5432/users-events
    username: dimmm
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog-master.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ttl: 60

server:
  port: 8087
