spring:
  application:
    name: redis-demo-my

  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres-db:5432/users-events
    username: dimmm
    password: 12345
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5
      initialization-fail-timeout: 0

  jpa:
    hibernate:
      ddl-auto: validate
#    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db-changelog.yaml

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      ttl: 60

server:
  port: 8087
  address: 0.0.0.0

app:
  jwt:
    secret: ${JWT_SECRET:SuperSecret1234567890-000000-2222222-00000-fdfdfddsfsfsdf}
    ttl: 900

  oauth2:
    client_id: ${GITHUB_CLIENT_ID}
    client_secret: ${GITHUB_CLIENT_SECRET}

  kafka:
    group-id: ${KAFKA_CONSUMER_GROUP_ID:events-consumer-group}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-broker:9092}
    trusted-packages: com.example.redis_demo_my.*
    topic:
      name: ${KAFKA_TOPIC_NAME:events}
      partitions: ${KAFKA_TOPIC_PARTITIONS:1}
      replicas: ${KAFKA_TOPIC_REPLICAS:1}