name: Manual Deploy to EC2 via Lambda+SSM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  trigger-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS Lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Invoke Lambda function
        run: |
          aws lambda invoke \
            --function-name your-lambda-name \
            --payload '{}' \
            --cli-binary-format raw-in-base64-out \
            lambda-response.json
          cat lambda-response.json
