name: Manual Deploy to EC2 via Lambda+SSM

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'

jobs:
  trigger-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger AWS Lambda
        uses: aws-actions/aws-cli-action@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

          inline: |
            aws lambda invoke \
              --function-name ec2-trigger-github-deployment \
              --payload '{}' \
              --cli-binary-format raw-in-base64-out \
              response.json
            cat response.json
